# Testing API

In [18]:
import requests
import json
import time
import jwt

In [28]:
payload = {
        "iss": "inanalysis.com",
        "iat": int(time.time()),
        "exp": int(time.time()) + 3600,
        "aud": "www.inanalysis.com"
}
token = jwt.encode(payload, "iloveraid1", algorithm='HS256').decode('utf-8')

In [36]:
form={"token":token,
      "fileUid":"num",
      "dataType":"num",
      "projectType":"regression",
      "algoName":"in_stopTest",
      "param":'{"fit_intercept":0,"normalize":0}',
      "input":'{"X":["a"]}',
      "output":'{"Y":"b"}'
     }

In [37]:
a=requests.post("http://140.112.26.132:8003/analytic/train",data=form)

In [38]:
a.content

b'{\n    "status": "success",\n    "msg": "",\n    "data": {\n        "modelUid": "a4402594-d44c-11e9-9169-9c5c8ebbb826"\n    }\n}\n'

In [41]:
form={"token":token,
      "modelUid":"a4402594-d44c-11e9-9169-9c5c8ebbb826",
      "fileUid":"num",
      "preprocess":1
     }
a=requests.delete("http://140.112.26.132:8003/analytic/stop",data=form)

In [42]:
a.content

b'{\n    "status": "error",\n    "msg": "model a4402594-d44c-11e9-9169-9c5c8ebbb826 not found in thread",\n    "data": {}\n}\n'

In [152]:
print(json.loads(a.content)['data']['text'])

c:
  Cross Entropy: 0.8994645813041956
  Report:
   +-------+-----------+--------+--------+---------+
   | Label | Precision | Recall | FScore | Support |
   +=======+===========+========+========+=========+
   | 2     | 0.400     | 1      | 0.571  | 2       |
   +-------+-----------+--------+--------+---------+
   | 3     | 0         | 0      | 0      | 2       |
   +-------+-----------+--------+--------+---------+
   | 5     | 1         | 0.667  | 0.800  | 3       |
   +-------+-----------+--------+--------+---------+



# Pandas and Numpy Playground

In [1]:
import pandas as pd
df=pd.read_csv('../db/num.csv')

In [2]:
df

a  b      c
0  1  2    NaN
1  2  5    2.0
2  1  7    1.0
3  3  7    3.0
4  1  1  100.0
5  2  4    2.0
6  3  9    3.0

In [13]:
import numpy as np

In [18]:
mse = np.sqrt(np.abs((df['a'] - df['b'])).mean())

In [19]:
mse

1.7728105208558367

In [5]:
df['aa']=[1,2,3,4,5,6,7]

In [6]:
df

a  b      c  test  aa
0  1  2    NaN     1   1
1  2  5    2.0     2   2
2  1  7    1.0     3   3
3  3  7    3.0     4   4
4  1  1  100.0     5   5
5  2  4    2.0     6   6
6  3  9    3.0     7   7

In [8]:
df.to_csv('./out.csv',index=None)

In [21]:
df.corr(method='pearson')

a         b         c
a  1.000000  0.705858 -0.531948
b  0.705858  1.000000 -0.779570
c -0.531948 -0.779570  1.000000

In [13]:
df.columns.tolist()

[]

In [133]:
df['a']=[1,2,3,4,5,6,7]

In [126]:
import numpy as np
a=np.asarray(df['a'])

In [127]:
b=np.asarray([True,True,False,True,True,True,True])

In [154]:
a=np.asarray(['b',,1,2,3,4,5])

In [155]:
set(a)

{1, 2, 3, 4, 5}

In [157]:
[{"original":o,"converted":c} for c,o in enumerate(set(a))]

[{'original': 1, 'converted': 0},
 {'original': 2, 'converted': 1},
 {'original': 3, 'converted': 2},
 {'original': 4, 'converted': 3},
 {'original': 5, 'converted': 4}]

In [145]:
from keras.utils import to_categorical
to_categorical(a)

ValueError: invalid literal for int() with base 10: 'a'

In [26]:
c2d={'1':'a','2':'b','3':'c'}
d2c={'a':1,'b':2,'c':3}

In [27]:
import numpy as np
real=[1,1,1,2,2,2,3,3,3]
predicted=[1,1,3,2,2,3,1,2,3]
from sklearn.metrics import confusion_matrix
realL=[c2d[str(i)] for i in real]
predictedL=[c2d[str(i)] for i in predicted]
label=[k for k in d2c]
cmx=confusion_matrix(realL,predictedL,labels=label)
cmx=cmx.astype('float')/cmx.sum(axis=1)[:,np.newaxis]

In [28]:
cmx

array([[0.66666667, 0.        , 0.33333333],
       [0.        , 0.66666667, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [30]:
import pandas as pd
df=pd.DataFrame(cmx,columns=label)

In [31]:
from service.visualizeService.core.analyticVizAlgo.heatmap import heatmap

In [32]:
algo=heatmap(df,"cmx",color='blue',xName='predict',yName='real')

In [33]:
algo.doBokehViz()

In [34]:
from bokeh.plotting import  show
show(algo.bokeh_fig)

In [1]:
from service.visualizeService.core.analyticVizAlgo.dotLineSelect import dotLineSelect

In [2]:
x={
    "xa":[1,2,3,4,5,6,7,8,9],
    "xb":[2,3,4,5,6,7,8,9,10]
}
dot={
    "ya":[4,5,7,6,3,4,2,1,5],
    "yb":[12,5,6,4,13,10,-1,5,4]
}
line={
    "ya":[3,4,6,5,2,3,1,0,4],
    "yb":[11,4,5,3,12,9,-2,4,3]
}

In [3]:
algo=dotLineSelect(x,dot,line)

In [4]:
algo.doBokehViz()

In [5]:
from bokeh.plotting import  show
show(algo.bokeh_fig)

In [1]:
from sklearn.ensemble import IsolationForest

In [7]:
import numpy as np
a=np.asarray([[1,2,3],[1,2,3],[11,12,13]])

In [8]:
model=IsolationForest()

In [9]:
model.fit(a)

IsolationForest(bootstrap=False, contamination=0.1, max_features=1.0,
        max_samples='auto', n_estimators=100, n_jobs=1, random_state=None,
        verbose=0)

In [10]:
model.predict(a)

array([-1, -1,  1])

In [11]:
model.predict([[11,12,13]])

array([1])

In [13]:
import pandas as pd
a=[[1,2],[3,4]]
b=pd.DataFrame(a,columns=[-1,1])

In [14]:
b

-1   1
0   1   2
1   3   4

In [15]:
b.to_csv('atest.csv',index=False)

# python-gmail

In [14]:
from __future__ import print_function
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/gmail.send','https://mail.google.com/']


"""Shows basic usage of the Gmail API.
Lists the user's Gmail labels.
"""
creds = None
# The file token.pickle stores the user's access and refresh tokens, and is
# created automatically when the authorization flow completes for the first
# time.
if os.path.exists('google_token.pickle'):
    with open('google_token.pickle', 'rb') as token:
        creds = pickle.load(token)
# If there are no (valid) credentials available, let the user log in.
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'client_secret.json', SCOPES)
        creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open('google_token.pickle', 'wb') as token:
        pickle.dump(creds, token)

service = build('gmail', 'v1', credentials=creds)

# Call the Gmail API
results = service.users().labels().list(userId='me').execute()
labels = results.get('labels', [])

if not labels:
    print('No labels found.')
else:
    print('Labels:')
    for label in labels:
        print(label['name'])


Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=429029828634-u4eeqa6eoecs4g6kf6e937ffhio7004u.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A55250%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.send+https%3A%2F%2Fmail.google.com%2F&state=RUvlywFNvV63f6yBX7q1LNSVkmL3pE&access_type=offline&code_challenge=nfXWA5g5OX_L73x4-kGeqi3BctGXKyXpLTuIXXf5FmM&code_challenge_method=S256
Labels:
CATEGORY_PERSONAL
CATEGORY_SOCIAL
IMPORTANT
CATEGORY_UPDATES
CATEGORY_FORUMS
CHAT
SENT
INBOX
TRASH
CATEGORY_PROMOTIONS
DRAFT
SPAM
STARRED
UNREAD


In [12]:
from email.mime.text import MIMEText
import base64
import json
# from __future__ import print_function
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/gmail.send','https://mail.google.com/']
creds=None
if os.path.exists('google_token.pickle'):
    with open('google_token.pickle', 'rb') as token:
        creds = pickle.load(token)
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'client_secret.json', SCOPES)
        creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open('google_token.pickle', 'wb') as token:
        pickle.dump(creds, token)
service = build('gmail', 'v1', credentials=creds)
txt="i love raid1"
msg = MIMEText(txt)
msg['to'] = 'kevinlin1168@gmail.com'
msg['from'] = 'inanalysis.github.io@gmail.com'
msg['subject'] = "LOVE"
raw = base64.urlsafe_b64encode(msg.as_bytes())
raw = raw.decode()
body = {'raw': raw}

# msg={'raw': base64.urlsafe_b64encode(byte(msg.as_string()))}
message = (service.users().messages().send(userId="me", body=body).execute())